//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.225
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.225.
// 
#pragma warning disable 1591

namespace CapaControl.ConsultasParametricas {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'validation' del espacio de nombres 'http://mynamespace'.
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'validation' del espacio de nombres 'http://mynamespace'.
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'validation' del espacio de nombres 'http://mynamespace'.
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'validation' del espacio de nombres 'http://mynamespace'.
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'validation' del espacio de nombres 'http://mynamespace'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Administrador_AdministradorParametricas_ConsultasParametricasSoap", Namespace="http://tempuri.org/")]
    public partial class Administrador_AdministradorParametricas_ConsultasParametricas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private inHeader inHeaderValueField;
        
        private System.Threading.SendOrPostCallback TablasFormulariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback AnexosPorTransaccionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CamposPorTransaccionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaldoPorItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback DatosPorItemOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Administrador_AdministradorParametricas_ConsultasParametricas() {
            this.Url = global::CapaControl.Properties.Settings.Default.CapaControl_UNOEE_WSUNOEE;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public inHeader inHeaderValue {
            get {
                return this.inHeaderValueField;
            }
            set {
                this.inHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TablasFormulariosCompletedEventHandler TablasFormulariosCompleted;
        
        /// <remarks/>
        public event AnexosPorTransaccionesCompletedEventHandler AnexosPorTransaccionesCompleted;
        
        /// <remarks/>
        public event CamposPorTransaccionCompletedEventHandler CamposPorTransaccionCompleted;
        
        /// <remarks/>
        public event SaldoPorItemCompletedEventHandler SaldoPorItemCompleted;
        
        /// <remarks/>
        public event DatosPorItemCompletedEventHandler DatosPorItemCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("inHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Administrador_AdministradorParametricas_ConsultasParametricas/" +
            "TablasFormularios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("TABLASPARAMETRICAS", Namespace="http://Mensajes.TablasParametricas")]
        public typeTablasParametricas TablasFormularios([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Mensajes.TablasParametricas")] typeFiltroTablaParametrica FILTROTABLAPARAMETRICA) {
            object[] results = this.Invoke("TablasFormularios", new object[] {
                        FILTROTABLAPARAMETRICA});
            return ((typeTablasParametricas)(results[0]));
        }
        
        /// <remarks/>
        public void TablasFormulariosAsync(typeFiltroTablaParametrica FILTROTABLAPARAMETRICA) {
            this.TablasFormulariosAsync(FILTROTABLAPARAMETRICA, null);
        }
        
        /// <remarks/>
        public void TablasFormulariosAsync(typeFiltroTablaParametrica FILTROTABLAPARAMETRICA, object userState) {
            if ((this.TablasFormulariosOperationCompleted == null)) {
                this.TablasFormulariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTablasFormulariosOperationCompleted);
            }
            this.InvokeAsync("TablasFormularios", new object[] {
                        FILTROTABLAPARAMETRICA}, this.TablasFormulariosOperationCompleted, userState);
        }
        
        private void OnTablasFormulariosOperationCompleted(object arg) {
            if ((this.TablasFormulariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TablasFormulariosCompleted(this, new TablasFormulariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("inHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Administrador_AdministradorParametricas_ConsultasParametricas/" +
            "AnexosPorTransacciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ANEXOSXTRANSACCION", Namespace="http://Mensajes.AnexosXTransaccion")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ANEXO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ANEXOSXTRANSACCIONANEXO[] AnexosPorTransacciones([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Mensajes.FiltroTransaccionAnexo")] FILTROTRANSACCION FILTROTRANSACCION) {
            object[] results = this.Invoke("AnexosPorTransacciones", new object[] {
                        FILTROTRANSACCION});
            return ((ANEXOSXTRANSACCIONANEXO[])(results[0]));
        }
        
        /// <remarks/>
        public void AnexosPorTransaccionesAsync(FILTROTRANSACCION FILTROTRANSACCION) {
            this.AnexosPorTransaccionesAsync(FILTROTRANSACCION, null);
        }
        
        /// <remarks/>
        public void AnexosPorTransaccionesAsync(FILTROTRANSACCION FILTROTRANSACCION, object userState) {
            if ((this.AnexosPorTransaccionesOperationCompleted == null)) {
                this.AnexosPorTransaccionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAnexosPorTransaccionesOperationCompleted);
            }
            this.InvokeAsync("AnexosPorTransacciones", new object[] {
                        FILTROTRANSACCION}, this.AnexosPorTransaccionesOperationCompleted, userState);
        }
        
        private void OnAnexosPorTransaccionesOperationCompleted(object arg) {
            if ((this.AnexosPorTransaccionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AnexosPorTransaccionesCompleted(this, new AnexosPorTransaccionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("inHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Administrador_AdministradorParametricas_ConsultasParametricas/" +
            "CamposPorTransaccion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("CAMPOSXTRANSACCION", Namespace="http://Mensajes.CamposXTransaccion")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("CAMPOXTRANSACCION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CAMPOSXTRANSACCIONCAMPOXTRANSACCION[] CamposPorTransaccion([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Mensajes.CamposXTransaccion")] FILTROTRANSACCION1 FILTROTRANSACCION) {
            object[] results = this.Invoke("CamposPorTransaccion", new object[] {
                        FILTROTRANSACCION});
            return ((CAMPOSXTRANSACCIONCAMPOXTRANSACCION[])(results[0]));
        }
        
        /// <remarks/>
        public void CamposPorTransaccionAsync(FILTROTRANSACCION1 FILTROTRANSACCION) {
            this.CamposPorTransaccionAsync(FILTROTRANSACCION, null);
        }
        
        /// <remarks/>
        public void CamposPorTransaccionAsync(FILTROTRANSACCION1 FILTROTRANSACCION, object userState) {
            if ((this.CamposPorTransaccionOperationCompleted == null)) {
                this.CamposPorTransaccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCamposPorTransaccionOperationCompleted);
            }
            this.InvokeAsync("CamposPorTransaccion", new object[] {
                        FILTROTRANSACCION}, this.CamposPorTransaccionOperationCompleted, userState);
        }
        
        private void OnCamposPorTransaccionOperationCompleted(object arg) {
            if ((this.CamposPorTransaccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CamposPorTransaccionCompleted(this, new CamposPorTransaccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("inHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Administrador_AdministradorParametricas_ConsultasParametricas/" +
            "SaldoPorItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESULTADOSALDOITEM", Namespace="http://Mensajes.TablasParametricas.ResultadoSaldoItem")]
        public RESULTADOSALDOITEM SaldoPorItem([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Mensajes.TablasParametricas.SaldoItem")] SALDOITEM SALDOITEM) {
            object[] results = this.Invoke("SaldoPorItem", new object[] {
                        SALDOITEM});
            return ((RESULTADOSALDOITEM)(results[0]));
        }
        
        /// <remarks/>
        public void SaldoPorItemAsync(SALDOITEM SALDOITEM) {
            this.SaldoPorItemAsync(SALDOITEM, null);
        }
        
        /// <remarks/>
        public void SaldoPorItemAsync(SALDOITEM SALDOITEM, object userState) {
            if ((this.SaldoPorItemOperationCompleted == null)) {
                this.SaldoPorItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaldoPorItemOperationCompleted);
            }
            this.InvokeAsync("SaldoPorItem", new object[] {
                        SALDOITEM}, this.SaldoPorItemOperationCompleted, userState);
        }
        
        private void OnSaldoPorItemOperationCompleted(object arg) {
            if ((this.SaldoPorItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaldoPorItemCompleted(this, new SaldoPorItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("inHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Administrador_AdministradorParametricas_ConsultasParametricas/" +
            "DatosPorItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESULTADODATOSITEM", Namespace="http://Mensajes.TablasParametricas.ResultadoDatosItem")]
        public RESULTADODATOSITEM DatosPorItem([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Mensajes.TablasParametricas.DatosItem")] DATOSITEM DATOSITEM) {
            object[] results = this.Invoke("DatosPorItem", new object[] {
                        DATOSITEM});
            return ((RESULTADODATOSITEM)(results[0]));
        }
        
        /// <remarks/>
        public void DatosPorItemAsync(DATOSITEM DATOSITEM) {
            this.DatosPorItemAsync(DATOSITEM, null);
        }
        
        /// <remarks/>
        public void DatosPorItemAsync(DATOSITEM DATOSITEM, object userState) {
            if ((this.DatosPorItemOperationCompleted == null)) {
                this.DatosPorItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDatosPorItemOperationCompleted);
            }
            this.InvokeAsync("DatosPorItem", new object[] {
                        DATOSITEM}, this.DatosPorItemOperationCompleted, userState);
        }
        
        private void OnDatosPorItemOperationCompleted(object arg) {
            if ((this.DatosPorItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DatosPorItemCompleted(this, new DatosPorItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.General.inHeader")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://Mensajes.General.inHeader", IsNullable=false)]
    public partial class inHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string cDCIAUSUARIAField;
        
        private string cDZONAFRANCAField;
        
        private string dSUSUARIOField;
        
        private string pWDUSUARIOField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDCIAUSUARIA {
            get {
                return this.cDCIAUSUARIAField;
            }
            set {
                this.cDCIAUSUARIAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string CDZONAFRANCA {
            get {
                return this.cDZONAFRANCAField;
            }
            set {
                this.cDZONAFRANCAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DSUSUARIO {
            get {
                return this.dSUSUARIOField;
            }
            set {
                this.dSUSUARIOField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PWDUSUARIO {
            get {
                return this.pWDUSUARIOField;
            }
            set {
                this.pWDUSUARIOField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mensajes.TablasParametricas")]
    public partial class typeEsMatriz {
        
        private string cDESMATRIZField;
        
        private string dSESMATRIZField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDESMATRIZ {
            get {
                return this.cDESMATRIZField;
            }
            set {
                this.cDESMATRIZField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DSESMATRIZ {
            get {
                return this.dSESMATRIZField;
            }
            set {
                this.dSESMATRIZField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mensajes.TablasParametricas")]
    public partial class typeSia {
        
        private string cDNITField;
        
        private string dSNOMBRESIAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDNIT {
            get {
                return this.cDNITField;
            }
            set {
                this.cDNITField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DSNOMBRESIA {
            get {
                return this.dSNOMBRESIAField;
            }
            set {
                this.dSNOMBRESIAField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mensajes.TablasParametricas")]
    public partial class typePais {
        
        private string cDPAISField;
        
        private string dSPAISField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDPAIS {
            get {
                return this.cDPAISField;
            }
            set {
                this.cDPAISField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DSPAIS {
            get {
                return this.dSPAISField;
            }
            set {
                this.dSPAISField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mensajes.TablasParametricas")]
    public partial class typeTransaccion {
        
        private string cDTRANSACCIONField;
        
        private string dSTRANSACCIONField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDTRANSACCION {
            get {
                return this.cDTRANSACCIONField;
            }
            set {
                this.cDTRANSACCIONField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DSTRANSACCION {
            get {
                return this.dSTRANSACCIONField;
            }
            set {
                this.dSTRANSACCIONField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mensajes.TablasParametricas")]
    public partial class typeSeccionalArancelaria {
        
        private int cDTIPOMERCANCIAField;
        
        private bool cDTIPOMERCANCIAFieldSpecified;
        
        private string dSTIPOMERCANCIAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int CDTIPOMERCANCIA {
            get {
                return this.cDTIPOMERCANCIAField;
            }
            set {
                this.cDTIPOMERCANCIAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CDTIPOMERCANCIASpecified {
            get {
                return this.cDTIPOMERCANCIAFieldSpecified;
            }
            set {
                this.cDTIPOMERCANCIAFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DSTIPOMERCANCIA {
            get {
                return this.dSTIPOMERCANCIAField;
            }
            set {
                this.dSTIPOMERCANCIAField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mensajes.TablasParametricas")]
    public partial class typeSubpartida {
        
        private string cDSUBPARTIDAField;
        
        private string dSSUBPARTIDAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDSUBPARTIDA {
            get {
                return this.cDSUBPARTIDAField;
            }
            set {
                this.cDSUBPARTIDAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DSSUBPARTIDA {
            get {
                return this.dSSUBPARTIDAField;
            }
            set {
                this.dSSUBPARTIDAField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mensajes.TablasParametricas")]
    public partial class typeTipoItem {
        
        private string cDTIPOField;
        
        private string dSTIPOField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDTIPO {
            get {
                return this.cDTIPOField;
            }
            set {
                this.cDTIPOField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DSTIPO {
            get {
                return this.dSTIPOField;
            }
            set {
                this.dSTIPOField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mensajes.TablasParametricas")]
    public partial class typeUnidadMedida {
        
        private string cDUNIDAField;
        
        private string dSCORTAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDUNIDA {
            get {
                return this.cDUNIDAField;
            }
            set {
                this.cDUNIDAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DSCORTA {
            get {
                return this.dSCORTAField;
            }
            set {
                this.dSCORTAField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mensajes.TablasParametricas")]
    public partial class typeImportador {
        
        private string cDNITField;
        
        private string dSNOMBREIMPORTADORField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDNIT {
            get {
                return this.cDNITField;
            }
            set {
                this.cDNITField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DSNOMBREIMPORTADOR {
            get {
                return this.dSNOMBREIMPORTADORField;
            }
            set {
                this.dSNOMBREIMPORTADORField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mensajes.TablasParametricas")]
    public partial class typeTablasParametricas {
        
        private typeImportador[] iMPORTADORESField;
        
        private typeUnidadMedida[] uNIDADESMEDIDAField;
        
        private typeTipoItem[] tIPOSITEMField;
        
        private typeSubpartida[] sUBPARTIDASField;
        
        private typeSeccionalArancelaria[] tIPOSMERCANCIASField;
        
        private typeTransaccion[] tRANSACCIONESField;
        
        private typePais[] pAISESField;
        
        private typeSia[] sIASField;
        
        private typeEsMatriz[] vALORESESMATRIZField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("IMPORTADOR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public typeImportador[] IMPORTADORES {
            get {
                return this.iMPORTADORESField;
            }
            set {
                this.iMPORTADORESField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("UNIDADMEDIDA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public typeUnidadMedida[] UNIDADESMEDIDA {
            get {
                return this.uNIDADESMEDIDAField;
            }
            set {
                this.uNIDADESMEDIDAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TIPOITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public typeTipoItem[] TIPOSITEM {
            get {
                return this.tIPOSITEMField;
            }
            set {
                this.tIPOSITEMField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SUBPARTIDA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public typeSubpartida[] SUBPARTIDAS {
            get {
                return this.sUBPARTIDASField;
            }
            set {
                this.sUBPARTIDASField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TIPOMERCANCIA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public typeSeccionalArancelaria[] TIPOSMERCANCIAS {
            get {
                return this.tIPOSMERCANCIASField;
            }
            set {
                this.tIPOSMERCANCIASField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TRANSACCION", IsNullable=false)]
        public typeTransaccion[] TRANSACCIONES {
            get {
                return this.tRANSACCIONESField;
            }
            set {
                this.tRANSACCIONESField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PAIS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public typePais[] PAISES {
            get {
                return this.pAISESField;
            }
            set {
                this.pAISESField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SIA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public typeSia[] SIAS {
            get {
                return this.sIASField;
            }
            set {
                this.sIASField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ESMATRIZ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public typeEsMatriz[] VALORESESMATRIZ {
            get {
                return this.vALORESESMATRIZField;
            }
            set {
                this.vALORESESMATRIZField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mensajes.TablasParametricas")]
    public partial class typeFiltroTablaParametrica {
        
        private typeEnumTablaParametrica tABLAPARAMETRICAField;
        
        private bool tABLAPARAMETRICAFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public typeEnumTablaParametrica TABLAPARAMETRICA {
            get {
                return this.tABLAPARAMETRICAField;
            }
            set {
                this.tABLAPARAMETRICAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TABLAPARAMETRICASpecified {
            get {
                return this.tABLAPARAMETRICAFieldSpecified;
            }
            set {
                this.tABLAPARAMETRICAFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mensajes.TablasParametricas")]
    public enum typeEnumTablaParametrica {
        
        /// <comentarios/>
        Todas,
        
        /// <comentarios/>
        TipoMercancia,
        
        /// <comentarios/>
        TipoItem,
        
        /// <comentarios/>
        UnidadMedida,
        
        /// <comentarios/>
        SubPartidaArancelaria,
        
        /// <comentarios/>
        EsMatriz,
        
        /// <comentarios/>
        Importador,
        
        /// <comentarios/>
        Sia,
        
        /// <comentarios/>
        Pais,
        
        /// <comentarios/>
        Transaccion,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.FiltroTransaccionAnexo")]
    public partial class FILTROTRANSACCION {
        
        private string cDTRANField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDTRAN {
            get {
                return this.cDTRANField;
            }
            set {
                this.cDTRANField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.AnexosXTransaccion")]
    public partial class ANEXOSXTRANSACCIONANEXO {
        
        private string cDANEXOField;
        
        private string dSANEXOField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDANEXO {
            get {
                return this.cDANEXOField;
            }
            set {
                this.cDANEXOField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DSANEXO {
            get {
                return this.dSANEXOField;
            }
            set {
                this.dSANEXOField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.CamposXTransaccion")]
    public partial class FILTROTRANSACCION1 {
        
        private string cDTRANField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDTRAN {
            get {
                return this.cDTRANField;
            }
            set {
                this.cDTRANField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.CamposXTransaccion")]
    public partial class CAMPOSXTRANSACCIONCAMPOXTRANSACCION {
        
        private string cDTRANSACCIONField;
        
        private string cDCAMPOField;
        
        private string dSCAMPOField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDTRANSACCION {
            get {
                return this.cDTRANSACCIONField;
            }
            set {
                this.cDTRANSACCIONField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDCAMPO {
            get {
                return this.cDCAMPOField;
            }
            set {
                this.cDCAMPOField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DSCAMPO {
            get {
                return this.dSCAMPOField;
            }
            set {
                this.dSCAMPOField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.TablasParametricas.SaldoItem")]
    public partial class SALDOITEM {
        
        private string cDITEMField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDITEM {
            get {
                return this.cDITEMField;
            }
            set {
                this.cDITEMField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.TablasParametricas.ResultadoSaldoItem")]
    public partial class RESULTADOSALDOITEM {
        
        private string nMSALDOField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NMSALDO {
            get {
                return this.nMSALDOField;
            }
            set {
                this.nMSALDOField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.TablasParametricas.DatosItem")]
    public partial class DATOSITEM {
        
        private string cDITEMField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDITEM {
            get {
                return this.cDITEMField;
            }
            set {
                this.cDITEMField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.TablasParametricas.ResultadoDatosItem")]
    public partial class RESULTADODATOSITEM {
        
        private string nREGField;
        
        private string cDCIA_USUARIAField;
        
        private string dSCIA_USUARIAField;
        
        private string cDITEMField;
        
        private string cDTIPO_MERCANCIAField;
        
        private string dSTIPO_MERCANCIAField;
        
        private string dSITEMField;
        
        private string cDTIPOField;
        
        private string dSTIPOField;
        
        private string cDSUBPARTIDAField;
        
        private string dSSUBPARTIDAField;
        
        private string cDUNIDAD_COMERCIALField;
        
        private string dSUNIDAD_COMERCIALField;
        
        private string cDUNIDAD_MEDField;
        
        private string dSUNIDAD_MEDField;
        
        private decimal nMCONVERSIONField;
        
        private string sNCOMPONENTESField;
        
        private string sNREEMPAQUEField;
        
        private string fEAPROBACIONField;
        
        private string fERETIROField;
        
        private decimal nMSALDO_INICIALField;
        
        private decimal nMSALDOField;
        
        private string idField;
        
        private string cHKSELECTField;
        
        private decimal sALDO_REALField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string NREG {
            get {
                return this.nREGField;
            }
            set {
                this.nREGField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDCIA_USUARIA {
            get {
                return this.cDCIA_USUARIAField;
            }
            set {
                this.cDCIA_USUARIAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DSCIA_USUARIA {
            get {
                return this.dSCIA_USUARIAField;
            }
            set {
                this.dSCIA_USUARIAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDITEM {
            get {
                return this.cDITEMField;
            }
            set {
                this.cDITEMField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDTIPO_MERCANCIA {
            get {
                return this.cDTIPO_MERCANCIAField;
            }
            set {
                this.cDTIPO_MERCANCIAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DSTIPO_MERCANCIA {
            get {
                return this.dSTIPO_MERCANCIAField;
            }
            set {
                this.dSTIPO_MERCANCIAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DSITEM {
            get {
                return this.dSITEMField;
            }
            set {
                this.dSITEMField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDTIPO {
            get {
                return this.cDTIPOField;
            }
            set {
                this.cDTIPOField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DSTIPO {
            get {
                return this.dSTIPOField;
            }
            set {
                this.dSTIPOField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDSUBPARTIDA {
            get {
                return this.cDSUBPARTIDAField;
            }
            set {
                this.cDSUBPARTIDAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DSSUBPARTIDA {
            get {
                return this.dSSUBPARTIDAField;
            }
            set {
                this.dSSUBPARTIDAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDUNIDAD_COMERCIAL {
            get {
                return this.cDUNIDAD_COMERCIALField;
            }
            set {
                this.cDUNIDAD_COMERCIALField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DSUNIDAD_COMERCIAL {
            get {
                return this.dSUNIDAD_COMERCIALField;
            }
            set {
                this.dSUNIDAD_COMERCIALField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDUNIDAD_MED {
            get {
                return this.cDUNIDAD_MEDField;
            }
            set {
                this.cDUNIDAD_MEDField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DSUNIDAD_MED {
            get {
                return this.dSUNIDAD_MEDField;
            }
            set {
                this.dSUNIDAD_MEDField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal NMCONVERSION {
            get {
                return this.nMCONVERSIONField;
            }
            set {
                this.nMCONVERSIONField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SNCOMPONENTES {
            get {
                return this.sNCOMPONENTESField;
            }
            set {
                this.sNCOMPONENTESField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SNREEMPAQUE {
            get {
                return this.sNREEMPAQUEField;
            }
            set {
                this.sNREEMPAQUEField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FEAPROBACION {
            get {
                return this.fEAPROBACIONField;
            }
            set {
                this.fEAPROBACIONField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FERETIRO {
            get {
                return this.fERETIROField;
            }
            set {
                this.fERETIROField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal NMSALDO_INICIAL {
            get {
                return this.nMSALDO_INICIALField;
            }
            set {
                this.nMSALDO_INICIALField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal NMSALDO {
            get {
                return this.nMSALDOField;
            }
            set {
                this.nMSALDOField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CHKSELECT {
            get {
                return this.cHKSELECTField;
            }
            set {
                this.cHKSELECTField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SALDO_REAL {
            get {
                return this.sALDO_REALField;
            }
            set {
                this.sALDO_REALField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TablasFormulariosCompletedEventHandler(object sender, TablasFormulariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TablasFormulariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TablasFormulariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public typeTablasParametricas Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((typeTablasParametricas)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AnexosPorTransaccionesCompletedEventHandler(object sender, AnexosPorTransaccionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AnexosPorTransaccionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AnexosPorTransaccionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ANEXOSXTRANSACCIONANEXO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ANEXOSXTRANSACCIONANEXO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CamposPorTransaccionCompletedEventHandler(object sender, CamposPorTransaccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CamposPorTransaccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CamposPorTransaccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CAMPOSXTRANSACCIONCAMPOXTRANSACCION[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CAMPOSXTRANSACCIONCAMPOXTRANSACCION[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SaldoPorItemCompletedEventHandler(object sender, SaldoPorItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaldoPorItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaldoPorItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOSALDOITEM Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOSALDOITEM)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DatosPorItemCompletedEventHandler(object sender, DatosPorItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatosPorItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DatosPorItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADODATOSITEM Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADODATOSITEM)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591