//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SIO.WsGerboPRU {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSInterfaceAppSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseModelOfUF))]
    public partial class WSInterfaceApp : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback TestarWebServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncluirMaterialOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncluirOrdemProdMatOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncluirReqPlanejadaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSInterfaceApp() {
            this.Url = global::SIO.Properties.Settings.Default.SIO_WsGerboPRU_WSInterfaceApp;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TestarWebServiceCompletedEventHandler TestarWebServiceCompleted;
        
        /// <remarks/>
        public event IncluirMaterialCompletedEventHandler IncluirMaterialCompleted;
        
        /// <remarks/>
        public event IncluirOrdemProdMatCompletedEventHandler IncluirOrdemProdMatCompleted;
        
        /// <remarks/>
        public event IncluirReqPlanejadaCompletedEventHandler IncluirReqPlanejadaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestarWebService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UF[] TestarWebService() {
            object[] results = this.Invoke("TestarWebService", new object[0]);
            return ((UF[])(results[0]));
        }
        
        /// <remarks/>
        public void TestarWebServiceAsync() {
            this.TestarWebServiceAsync(null);
        }
        
        /// <remarks/>
        public void TestarWebServiceAsync(object userState) {
            if ((this.TestarWebServiceOperationCompleted == null)) {
                this.TestarWebServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestarWebServiceOperationCompleted);
            }
            this.InvokeAsync("TestarWebService", new object[0], this.TestarWebServiceOperationCompleted, userState);
        }
        
        private void OnTestarWebServiceOperationCompleted(object arg) {
            if ((this.TestarWebServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestarWebServiceCompleted(this, new TestarWebServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncluirMaterial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RetProductID IncluirMaterial(RegProduto produto) {
            object[] results = this.Invoke("IncluirMaterial", new object[] {
                        produto});
            return ((RetProductID)(results[0]));
        }
        
        /// <remarks/>
        public void IncluirMaterialAsync(RegProduto produto) {
            this.IncluirMaterialAsync(produto, null);
        }
        
        /// <remarks/>
        public void IncluirMaterialAsync(RegProduto produto, object userState) {
            if ((this.IncluirMaterialOperationCompleted == null)) {
                this.IncluirMaterialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncluirMaterialOperationCompleted);
            }
            this.InvokeAsync("IncluirMaterial", new object[] {
                        produto}, this.IncluirMaterialOperationCompleted, userState);
        }
        
        private void OnIncluirMaterialOperationCompleted(object arg) {
            if ((this.IncluirMaterialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncluirMaterialCompleted(this, new IncluirMaterialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncluirOrdemProdMat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RetOrdemProdID IncluirOrdemProdMat(RegOrdemProd ordemProd) {
            object[] results = this.Invoke("IncluirOrdemProdMat", new object[] {
                        ordemProd});
            return ((RetOrdemProdID)(results[0]));
        }
        
        /// <remarks/>
        public void IncluirOrdemProdMatAsync(RegOrdemProd ordemProd) {
            this.IncluirOrdemProdMatAsync(ordemProd, null);
        }
        
        /// <remarks/>
        public void IncluirOrdemProdMatAsync(RegOrdemProd ordemProd, object userState) {
            if ((this.IncluirOrdemProdMatOperationCompleted == null)) {
                this.IncluirOrdemProdMatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncluirOrdemProdMatOperationCompleted);
            }
            this.InvokeAsync("IncluirOrdemProdMat", new object[] {
                        ordemProd}, this.IncluirOrdemProdMatOperationCompleted, userState);
        }
        
        private void OnIncluirOrdemProdMatOperationCompleted(object arg) {
            if ((this.IncluirOrdemProdMatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncluirOrdemProdMatCompleted(this, new IncluirOrdemProdMatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncluirReqPlanejada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RetRequisicaoID IncluirReqPlanejada(RegRequisicao reqPlanejada) {
            object[] results = this.Invoke("IncluirReqPlanejada", new object[] {
                        reqPlanejada});
            return ((RetRequisicaoID)(results[0]));
        }
        
        /// <remarks/>
        public void IncluirReqPlanejadaAsync(RegRequisicao reqPlanejada) {
            this.IncluirReqPlanejadaAsync(reqPlanejada, null);
        }
        
        /// <remarks/>
        public void IncluirReqPlanejadaAsync(RegRequisicao reqPlanejada, object userState) {
            if ((this.IncluirReqPlanejadaOperationCompleted == null)) {
                this.IncluirReqPlanejadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncluirReqPlanejadaOperationCompleted);
            }
            this.InvokeAsync("IncluirReqPlanejada", new object[] {
                        reqPlanejada}, this.IncluirReqPlanejadaOperationCompleted, userState);
        }
        
        private void OnIncluirReqPlanejadaOperationCompleted(object arg) {
            if ((this.IncluirReqPlanejadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncluirReqPlanejadaCompleted(this, new IncluirReqPlanejadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string keyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RetRequisicaoID {
        
        private string cOD_EMPRESAField;
        
        private string cOD_DOCRQField;
        
        private string nUM_REQMATERIALField;
        
        private string dES_MSGRETORNOField;
        
        /// <comentarios/>
        public string COD_EMPRESA {
            get {
                return this.cOD_EMPRESAField;
            }
            set {
                this.cOD_EMPRESAField = value;
            }
        }
        
        /// <comentarios/>
        public string COD_DOCRQ {
            get {
                return this.cOD_DOCRQField;
            }
            set {
                this.cOD_DOCRQField = value;
            }
        }
        
        /// <comentarios/>
        public string NUM_REQMATERIAL {
            get {
                return this.nUM_REQMATERIALField;
            }
            set {
                this.nUM_REQMATERIALField = value;
            }
        }
        
        /// <comentarios/>
        public string DES_MSGRETORNO {
            get {
                return this.dES_MSGRETORNOField;
            }
            set {
                this.dES_MSGRETORNOField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RegRequisicao {
        
        private string codEmpresaField;
        
        private string codDocOPField;
        
        private string numOrdemProdField;
        
        private string codMaterialField;
        
        private decimal qtdNecessariaField;
        
        private string codCCustoReqField;
        
        private System.DateTime datNecessariaField;
        
        /// <comentarios/>
        public string CodEmpresa {
            get {
                return this.codEmpresaField;
            }
            set {
                this.codEmpresaField = value;
            }
        }
        
        /// <comentarios/>
        public string CodDocOP {
            get {
                return this.codDocOPField;
            }
            set {
                this.codDocOPField = value;
            }
        }
        
        /// <comentarios/>
        public string NumOrdemProd {
            get {
                return this.numOrdemProdField;
            }
            set {
                this.numOrdemProdField = value;
            }
        }
        
        /// <comentarios/>
        public string CodMaterial {
            get {
                return this.codMaterialField;
            }
            set {
                this.codMaterialField = value;
            }
        }
        
        /// <comentarios/>
        public decimal QtdNecessaria {
            get {
                return this.qtdNecessariaField;
            }
            set {
                this.qtdNecessariaField = value;
            }
        }
        
        /// <comentarios/>
        public string CodCCustoReq {
            get {
                return this.codCCustoReqField;
            }
            set {
                this.codCCustoReqField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime DatNecessaria {
            get {
                return this.datNecessariaField;
            }
            set {
                this.datNecessariaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RetOrdemProdID {
        
        private string cOD_EMPRESAField;
        
        private string cOD_DOCOPField;
        
        private string nUM_ORDEMPRODField;
        
        private string dES_MSGRETORNOField;
        
        /// <comentarios/>
        public string COD_EMPRESA {
            get {
                return this.cOD_EMPRESAField;
            }
            set {
                this.cOD_EMPRESAField = value;
            }
        }
        
        /// <comentarios/>
        public string COD_DOCOP {
            get {
                return this.cOD_DOCOPField;
            }
            set {
                this.cOD_DOCOPField = value;
            }
        }
        
        /// <comentarios/>
        public string NUM_ORDEMPROD {
            get {
                return this.nUM_ORDEMPRODField;
            }
            set {
                this.nUM_ORDEMPRODField = value;
            }
        }
        
        /// <comentarios/>
        public string DES_MSGRETORNO {
            get {
                return this.dES_MSGRETORNOField;
            }
            set {
                this.dES_MSGRETORNOField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RegOrdemProd {
        
        private string codEmpresaField;
        
        private string codDocOPField;
        
        private string tipProdutoField;
        
        private string codProdutoField;
        
        private decimal qtdProduzirField;
        
        private System.DateTime datInicioField;
        
        private System.DateTime datNecessariaField;
        
        private string codDocOPPaiField;
        
        private string numOrdemProdPaiField;
        
        private string nomUsuarioRespField;
        
        /// <comentarios/>
        public string CodEmpresa {
            get {
                return this.codEmpresaField;
            }
            set {
                this.codEmpresaField = value;
            }
        }
        
        /// <comentarios/>
        public string CodDocOP {
            get {
                return this.codDocOPField;
            }
            set {
                this.codDocOPField = value;
            }
        }
        
        /// <comentarios/>
        public string TipProduto {
            get {
                return this.tipProdutoField;
            }
            set {
                this.tipProdutoField = value;
            }
        }
        
        /// <comentarios/>
        public string CodProduto {
            get {
                return this.codProdutoField;
            }
            set {
                this.codProdutoField = value;
            }
        }
        
        /// <comentarios/>
        public decimal QtdProduzir {
            get {
                return this.qtdProduzirField;
            }
            set {
                this.qtdProduzirField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime DatInicio {
            get {
                return this.datInicioField;
            }
            set {
                this.datInicioField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime DatNecessaria {
            get {
                return this.datNecessariaField;
            }
            set {
                this.datNecessariaField = value;
            }
        }
        
        /// <comentarios/>
        public string CodDocOPPai {
            get {
                return this.codDocOPPaiField;
            }
            set {
                this.codDocOPPaiField = value;
            }
        }
        
        /// <comentarios/>
        public string NumOrdemProdPai {
            get {
                return this.numOrdemProdPaiField;
            }
            set {
                this.numOrdemProdPaiField = value;
            }
        }
        
        /// <comentarios/>
        public string NomUsuarioResp {
            get {
                return this.nomUsuarioRespField;
            }
            set {
                this.nomUsuarioRespField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RetProductID {
        
        private string cOD_EMPRESAField;
        
        private string tIP_PRODUTOField;
        
        private string cOD_PRODUTOField;
        
        private string dES_MSGRETORNOField;
        
        /// <comentarios/>
        public string COD_EMPRESA {
            get {
                return this.cOD_EMPRESAField;
            }
            set {
                this.cOD_EMPRESAField = value;
            }
        }
        
        /// <comentarios/>
        public string TIP_PRODUTO {
            get {
                return this.tIP_PRODUTOField;
            }
            set {
                this.tIP_PRODUTOField = value;
            }
        }
        
        /// <comentarios/>
        public string COD_PRODUTO {
            get {
                return this.cOD_PRODUTOField;
            }
            set {
                this.cOD_PRODUTOField = value;
            }
        }
        
        /// <comentarios/>
        public string DES_MSGRETORNO {
            get {
                return this.dES_MSGRETORNOField;
            }
            set {
                this.dES_MSGRETORNOField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RegProduto {
        
        private string codEmpresaField;
        
        private string tipProdutoField;
        
        private string codProdutoField;
        
        private string desProdutoField;
        
        private string sigUnidadeField;
        
        private string tipProcedenciaField;
        
        private string codLinhaField;
        
        private string codFamiliaField;
        
        private string codSubFamiliaField;
        
        private string codOriMercadField;
        
        private string desComplMatField;
        
        private string numClaFiscalField;
        
        private string numCtaEstoqueField;
        
        private string numCtaProducaoField;
        
        private string flgNumLoteField;
        
        private string flgSeriadoField;
        
        private string flgNaturezaField;
        
        private decimal valPBrutoUniField;
        
        private decimal valPliqUniField;
        
        private string numCtaVendaField;
        
        private string numCtaICMSField;
        
        private string numCtaIPIField;
        
        private string numCtaCustoVendaField;
        
        private string codTipoItemField;
        
        /// <comentarios/>
        public string CodEmpresa {
            get {
                return this.codEmpresaField;
            }
            set {
                this.codEmpresaField = value;
            }
        }
        
        /// <comentarios/>
        public string TipProduto {
            get {
                return this.tipProdutoField;
            }
            set {
                this.tipProdutoField = value;
            }
        }
        
        /// <comentarios/>
        public string CodProduto {
            get {
                return this.codProdutoField;
            }
            set {
                this.codProdutoField = value;
            }
        }
        
        /// <comentarios/>
        public string DesProduto {
            get {
                return this.desProdutoField;
            }
            set {
                this.desProdutoField = value;
            }
        }
        
        /// <comentarios/>
        public string SigUnidade {
            get {
                return this.sigUnidadeField;
            }
            set {
                this.sigUnidadeField = value;
            }
        }
        
        /// <comentarios/>
        public string TipProcedencia {
            get {
                return this.tipProcedenciaField;
            }
            set {
                this.tipProcedenciaField = value;
            }
        }
        
        /// <comentarios/>
        public string CodLinha {
            get {
                return this.codLinhaField;
            }
            set {
                this.codLinhaField = value;
            }
        }
        
        /// <comentarios/>
        public string CodFamilia {
            get {
                return this.codFamiliaField;
            }
            set {
                this.codFamiliaField = value;
            }
        }
        
        /// <comentarios/>
        public string CodSubFamilia {
            get {
                return this.codSubFamiliaField;
            }
            set {
                this.codSubFamiliaField = value;
            }
        }
        
        /// <comentarios/>
        public string CodOriMercad {
            get {
                return this.codOriMercadField;
            }
            set {
                this.codOriMercadField = value;
            }
        }
        
        /// <comentarios/>
        public string DesComplMat {
            get {
                return this.desComplMatField;
            }
            set {
                this.desComplMatField = value;
            }
        }
        
        /// <comentarios/>
        public string NumClaFiscal {
            get {
                return this.numClaFiscalField;
            }
            set {
                this.numClaFiscalField = value;
            }
        }
        
        /// <comentarios/>
        public string NumCtaEstoque {
            get {
                return this.numCtaEstoqueField;
            }
            set {
                this.numCtaEstoqueField = value;
            }
        }
        
        /// <comentarios/>
        public string NumCtaProducao {
            get {
                return this.numCtaProducaoField;
            }
            set {
                this.numCtaProducaoField = value;
            }
        }
        
        /// <comentarios/>
        public string FlgNumLote {
            get {
                return this.flgNumLoteField;
            }
            set {
                this.flgNumLoteField = value;
            }
        }
        
        /// <comentarios/>
        public string FlgSeriado {
            get {
                return this.flgSeriadoField;
            }
            set {
                this.flgSeriadoField = value;
            }
        }
        
        /// <comentarios/>
        public string FlgNatureza {
            get {
                return this.flgNaturezaField;
            }
            set {
                this.flgNaturezaField = value;
            }
        }
        
        /// <comentarios/>
        public decimal ValPBrutoUni {
            get {
                return this.valPBrutoUniField;
            }
            set {
                this.valPBrutoUniField = value;
            }
        }
        
        /// <comentarios/>
        public decimal ValPliqUni {
            get {
                return this.valPliqUniField;
            }
            set {
                this.valPliqUniField = value;
            }
        }
        
        /// <comentarios/>
        public string NumCtaVenda {
            get {
                return this.numCtaVendaField;
            }
            set {
                this.numCtaVendaField = value;
            }
        }
        
        /// <comentarios/>
        public string NumCtaICMS {
            get {
                return this.numCtaICMSField;
            }
            set {
                this.numCtaICMSField = value;
            }
        }
        
        /// <comentarios/>
        public string NumCtaIPI {
            get {
                return this.numCtaIPIField;
            }
            set {
                this.numCtaIPIField = value;
            }
        }
        
        /// <comentarios/>
        public string NumCtaCustoVenda {
            get {
                return this.numCtaCustoVendaField;
            }
            set {
                this.numCtaCustoVendaField = value;
            }
        }
        
        /// <comentarios/>
        public string CodTipoItem {
            get {
                return this.codTipoItemField;
            }
            set {
                this.codTipoItemField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UF))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class BaseModelOfUF {
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UF : BaseModelOfUF {
        
        private string sIG_UFField;
        
        private string dES_UFField;
        
        /// <comentarios/>
        public string SIG_UF {
            get {
                return this.sIG_UFField;
            }
            set {
                this.sIG_UFField = value;
            }
        }
        
        /// <comentarios/>
        public string DES_UF {
            get {
                return this.dES_UFField;
            }
            set {
                this.dES_UFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void TestarWebServiceCompletedEventHandler(object sender, TestarWebServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestarWebServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestarWebServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UF[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UF[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IncluirMaterialCompletedEventHandler(object sender, IncluirMaterialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncluirMaterialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncluirMaterialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetProductID Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetProductID)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IncluirOrdemProdMatCompletedEventHandler(object sender, IncluirOrdemProdMatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncluirOrdemProdMatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncluirOrdemProdMatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetOrdemProdID Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetOrdemProdID)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IncluirReqPlanejadaCompletedEventHandler(object sender, IncluirReqPlanejadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncluirReqPlanejadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncluirReqPlanejadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetRequisicaoID Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetRequisicaoID)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591