//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.21.0.108/WSUNOEE/WSUNOEE.asmx")]
        public string SIO_UNOEE_WSUNOEE {
            get {
                return ((string)(this["SIO_UNOEE_WSUNOEE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wsforsa.siesacloud.com:8043/WSUNOEE/WSUNOEE.asmx")]
        public string SIO_WsReal_WSUNOEE {
            get {
                return ((string)(this["SIO_WsReal_WSUNOEE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.21.0.1/wsGerbo/wsGerbo.asmx")]
        public string SIO_wsGerbo_WSInterfaceApp {
            get {
                return ((string)(this["SIO_wsGerbo_WSInterfaceApp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://177.185.11.24:8081/wsGerbo/wsGerbo.asmx")]
        public string SIO_WsGerboPRU_WSInterfaceApp {
            get {
                return ((string)(this["SIO_WsGerboPRU_WSInterfaceApp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wsforsa.siesacloud.com:8043/WSUNOEE/WSUNOEE.asmx")]
        public string SIO_com_siesacloud_wsforsa_WSUNOEE {
            get {
                return ((string)(this["SIO_com_siesacloud_wsforsa_WSUNOEE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wsforsapru.siesacloud.com:8043/WSUNOEE/WSUNOEE.asmx")]
        public string SIO_com_siesacloud_wsforsapru_WSUNOEE {
            get {
                return ((string)(this["SIO_com_siesacloud_wsforsapru_WSUNOEE"]));
            }
        }
    }
}
