//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.225
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.225.
// 
#pragma warning disable 1591

namespace CapaControl.MatricesItems {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'validation' del espacio de nombres 'http://mynamespace'.
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'validation' del espacio de nombres 'http://mynamespace'.
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'validation' del espacio de nombres 'http://mynamespace'.
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'validation' del espacio de nombres 'http://mynamespace'.
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'validation' del espacio de nombres 'http://mynamespace'.
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'validation' del espacio de nombres 'http://mynamespace'.
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'validation' del espacio de nombres 'http://mynamespace'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Administrador_AdministradorMatricesItems_MatricesItemsSoap", Namespace="http://tempuri.org/")]
    public partial class Administrador_AdministradorMatricesItems_MatricesItems : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private inHeader inHeaderValueField;
        
        private System.Threading.SendOrPostCallback ActualizarItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarComponenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarComponenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarComponenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarComponentePorEliminacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarComponentePorEliminacionMasivoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Administrador_AdministradorMatricesItems_MatricesItems() {
            this.Url = global::CapaControl.Properties.Settings.Default.CapaControl_WsReal_WSUNOEE;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public inHeader inHeaderValue {
            get {
                return this.inHeaderValueField;
            }
            set {
                this.inHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ActualizarItemCompletedEventHandler ActualizarItemCompleted;
        
        /// <remarks/>
        public event InsertarComponenteCompletedEventHandler InsertarComponenteCompleted;
        
        /// <remarks/>
        public event ModificarComponenteCompletedEventHandler ModificarComponenteCompleted;
        
        /// <remarks/>
        public event EliminarComponenteCompletedEventHandler EliminarComponenteCompleted;
        
        /// <remarks/>
        public event InsertarItemCompletedEventHandler InsertarItemCompleted;
        
        /// <remarks/>
        public event ModificarComponentePorEliminacionCompletedEventHandler ModificarComponentePorEliminacionCompleted;
        
        /// <remarks/>
        public event ModificarComponentePorEliminacionMasivoCompletedEventHandler ModificarComponentePorEliminacionMasivoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("inHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Administrador_AdministradorMatricesItems_MatricesItems/Actuali" +
            "zarItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESULTADOMATRICESITEMS", Namespace="http://Mensajes.MatricesItems.ResultadoMatricesItems")]
        public typeResultadoMatricesItems ActualizarItem([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Mensajes.MatricesItems.ActualizarItemsCompania")] ACTUALIZARITEMSCOMPANIA ACTUALIZARITEMSCOMPANIA) {
            object[] results = this.Invoke("ActualizarItem", new object[] {
                        ACTUALIZARITEMSCOMPANIA});
            return ((typeResultadoMatricesItems)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarItemAsync(ACTUALIZARITEMSCOMPANIA ACTUALIZARITEMSCOMPANIA) {
            this.ActualizarItemAsync(ACTUALIZARITEMSCOMPANIA, null);
        }
        
        /// <remarks/>
        public void ActualizarItemAsync(ACTUALIZARITEMSCOMPANIA ACTUALIZARITEMSCOMPANIA, object userState) {
            if ((this.ActualizarItemOperationCompleted == null)) {
                this.ActualizarItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarItemOperationCompleted);
            }
            this.InvokeAsync("ActualizarItem", new object[] {
                        ACTUALIZARITEMSCOMPANIA}, this.ActualizarItemOperationCompleted, userState);
        }
        
        private void OnActualizarItemOperationCompleted(object arg) {
            if ((this.ActualizarItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarItemCompleted(this, new ActualizarItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("inHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Administrador_AdministradorMatricesItems_MatricesItems/Inserta" +
            "rComponente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESULTADOMATRICESITEMS", Namespace="http://Mensajes.MatricesItems.ResultadoMatricesItems")]
        public typeResultadoMatricesItems InsertarComponente([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Mensajes.MatricesItems.Matriz")] MATRIZ MATRIZ) {
            object[] results = this.Invoke("InsertarComponente", new object[] {
                        MATRIZ});
            return ((typeResultadoMatricesItems)(results[0]));
        }
        
        /// <remarks/>
        public void InsertarComponenteAsync(MATRIZ MATRIZ) {
            this.InsertarComponenteAsync(MATRIZ, null);
        }
        
        /// <remarks/>
        public void InsertarComponenteAsync(MATRIZ MATRIZ, object userState) {
            if ((this.InsertarComponenteOperationCompleted == null)) {
                this.InsertarComponenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarComponenteOperationCompleted);
            }
            this.InvokeAsync("InsertarComponente", new object[] {
                        MATRIZ}, this.InsertarComponenteOperationCompleted, userState);
        }
        
        private void OnInsertarComponenteOperationCompleted(object arg) {
            if ((this.InsertarComponenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarComponenteCompleted(this, new InsertarComponenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("inHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Administrador_AdministradorMatricesItems_MatricesItems/Modific" +
            "arComponente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESULTADOMATRICESITEMS", Namespace="http://Mensajes.MatricesItems.ResultadoMatricesItems")]
        public typeResultadoMatricesItems ModificarComponente([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Mensajes.MatricesItems.Matriz")] MATRIZ MATRIZ) {
            object[] results = this.Invoke("ModificarComponente", new object[] {
                        MATRIZ});
            return ((typeResultadoMatricesItems)(results[0]));
        }
        
        /// <remarks/>
        public void ModificarComponenteAsync(MATRIZ MATRIZ) {
            this.ModificarComponenteAsync(MATRIZ, null);
        }
        
        /// <remarks/>
        public void ModificarComponenteAsync(MATRIZ MATRIZ, object userState) {
            if ((this.ModificarComponenteOperationCompleted == null)) {
                this.ModificarComponenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarComponenteOperationCompleted);
            }
            this.InvokeAsync("ModificarComponente", new object[] {
                        MATRIZ}, this.ModificarComponenteOperationCompleted, userState);
        }
        
        private void OnModificarComponenteOperationCompleted(object arg) {
            if ((this.ModificarComponenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarComponenteCompleted(this, new ModificarComponenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("inHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Administrador_AdministradorMatricesItems_MatricesItems/Elimina" +
            "rComponente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESULTADOMATRICESITEMS", Namespace="http://Mensajes.MatricesItems.ResultadoMatricesItems")]
        public typeResultadoMatricesItems EliminarComponente([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Mensajes.MatricesItems.InfoMatriz")] INFOMATRIZ INFOMATRIZ) {
            object[] results = this.Invoke("EliminarComponente", new object[] {
                        INFOMATRIZ});
            return ((typeResultadoMatricesItems)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarComponenteAsync(INFOMATRIZ INFOMATRIZ) {
            this.EliminarComponenteAsync(INFOMATRIZ, null);
        }
        
        /// <remarks/>
        public void EliminarComponenteAsync(INFOMATRIZ INFOMATRIZ, object userState) {
            if ((this.EliminarComponenteOperationCompleted == null)) {
                this.EliminarComponenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarComponenteOperationCompleted);
            }
            this.InvokeAsync("EliminarComponente", new object[] {
                        INFOMATRIZ}, this.EliminarComponenteOperationCompleted, userState);
        }
        
        private void OnEliminarComponenteOperationCompleted(object arg) {
            if ((this.EliminarComponenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarComponenteCompleted(this, new EliminarComponenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("inHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Administrador_AdministradorMatricesItems_MatricesItems/Inserta" +
            "rItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESULTADOMATRICESITEMS", Namespace="http://Mensajes.MatricesItems.ResultadoMatricesItems")]
        public typeResultadoMatricesItems InsertarItem([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Mensajes.MatricesItems.InsertarItemsCompania")] INSERTARITEMSCOMPANIA INSERTARITEMSCOMPANIA) {
            object[] results = this.Invoke("InsertarItem", new object[] {
                        INSERTARITEMSCOMPANIA});
            return ((typeResultadoMatricesItems)(results[0]));
        }
        
        /// <remarks/>
        public void InsertarItemAsync(INSERTARITEMSCOMPANIA INSERTARITEMSCOMPANIA) {
            this.InsertarItemAsync(INSERTARITEMSCOMPANIA, null);
        }
        
        /// <remarks/>
        public void InsertarItemAsync(INSERTARITEMSCOMPANIA INSERTARITEMSCOMPANIA, object userState) {
            if ((this.InsertarItemOperationCompleted == null)) {
                this.InsertarItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarItemOperationCompleted);
            }
            this.InvokeAsync("InsertarItem", new object[] {
                        INSERTARITEMSCOMPANIA}, this.InsertarItemOperationCompleted, userState);
        }
        
        private void OnInsertarItemOperationCompleted(object arg) {
            if ((this.InsertarItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarItemCompleted(this, new InsertarItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("inHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Administrador_AdministradorMatricesItems_MatricesItems/Modific" +
            "arComponentePorEliminacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESULTADOMATRICESITEMS", Namespace="http://Mensajes.MatricesItems.ResultadoMatricesItems")]
        public typeResultadoMatricesItems ModificarComponentePorEliminacion([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Mensajes.MatricesItems.Matriz")] MATRIZ MATRIZ) {
            object[] results = this.Invoke("ModificarComponentePorEliminacion", new object[] {
                        MATRIZ});
            return ((typeResultadoMatricesItems)(results[0]));
        }
        
        /// <remarks/>
        public void ModificarComponentePorEliminacionAsync(MATRIZ MATRIZ) {
            this.ModificarComponentePorEliminacionAsync(MATRIZ, null);
        }
        
        /// <remarks/>
        public void ModificarComponentePorEliminacionAsync(MATRIZ MATRIZ, object userState) {
            if ((this.ModificarComponentePorEliminacionOperationCompleted == null)) {
                this.ModificarComponentePorEliminacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarComponentePorEliminacionOperationCompleted);
            }
            this.InvokeAsync("ModificarComponentePorEliminacion", new object[] {
                        MATRIZ}, this.ModificarComponentePorEliminacionOperationCompleted, userState);
        }
        
        private void OnModificarComponentePorEliminacionOperationCompleted(object arg) {
            if ((this.ModificarComponentePorEliminacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarComponentePorEliminacionCompleted(this, new ModificarComponentePorEliminacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("inHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Administrador_AdministradorMatricesItems_MatricesItems/Modific" +
            "arComponentePorEliminacionMasivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESULTADOMATRICESITEMS", Namespace="http://Mensajes.MatricesItems.ResultadoMatricesItems")]
        public typeResultadoMatricesItems ModificarComponentePorEliminacionMasivo([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://Mensajes.MatricesItems.MatrizMasivo")] [System.Xml.Serialization.XmlArrayItemAttribute("MATRIZ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] MATRIZMATRIZ[] MATRIZ) {
            object[] results = this.Invoke("ModificarComponentePorEliminacionMasivo", new object[] {
                        MATRIZ});
            return ((typeResultadoMatricesItems)(results[0]));
        }
        
        /// <remarks/>
        public void ModificarComponentePorEliminacionMasivoAsync(MATRIZMATRIZ[] MATRIZ) {
            this.ModificarComponentePorEliminacionMasivoAsync(MATRIZ, null);
        }
        
        /// <remarks/>
        public void ModificarComponentePorEliminacionMasivoAsync(MATRIZMATRIZ[] MATRIZ, object userState) {
            if ((this.ModificarComponentePorEliminacionMasivoOperationCompleted == null)) {
                this.ModificarComponentePorEliminacionMasivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarComponentePorEliminacionMasivoOperationCompleted);
            }
            this.InvokeAsync("ModificarComponentePorEliminacionMasivo", new object[] {
                        MATRIZ}, this.ModificarComponentePorEliminacionMasivoOperationCompleted, userState);
        }
        
        private void OnModificarComponentePorEliminacionMasivoOperationCompleted(object arg) {
            if ((this.ModificarComponentePorEliminacionMasivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarComponentePorEliminacionMasivoCompleted(this, new ModificarComponentePorEliminacionMasivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.General.inHeader")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://Mensajes.General.inHeader", IsNullable=false)]
    public partial class inHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string cDCIAUSUARIAField;
        
        private string cDZONAFRANCAField;
        
        private string dSUSUARIOField;
        
        private string pWDUSUARIOField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDCIAUSUARIA {
            get {
                return this.cDCIAUSUARIAField;
            }
            set {
                this.cDCIAUSUARIAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string CDZONAFRANCA {
            get {
                return this.cDZONAFRANCAField;
            }
            set {
                this.cDZONAFRANCAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DSUSUARIO {
            get {
                return this.dSUSUARIOField;
            }
            set {
                this.dSUSUARIOField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PWDUSUARIO {
            get {
                return this.pWDUSUARIOField;
            }
            set {
                this.pWDUSUARIOField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mensajes.MatricesItems.ResultadoMatricesItems")]
    public partial class typeErrorMatricesItems {
        
        private string cDREGISTROField;
        
        private string dSCAMPOField;
        
        private string cDERRORField;
        
        private string dSMENSAJEField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDREGISTRO {
            get {
                return this.cDREGISTROField;
            }
            set {
                this.cDREGISTROField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DSCAMPO {
            get {
                return this.dSCAMPOField;
            }
            set {
                this.dSCAMPOField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDERROR {
            get {
                return this.cDERRORField;
            }
            set {
                this.cDERRORField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DSMENSAJE {
            get {
                return this.dSMENSAJEField;
            }
            set {
                this.dSMENSAJEField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mensajes.MatricesItems.ResultadoMatricesItems")]
    public partial class typeResultadoMatricesItems {
        
        private bool fGRESULTADOField;
        
        private string dSMENSAJEField;
        
        private typeErrorMatricesItems[] eRRORESField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool FGRESULTADO {
            get {
                return this.fGRESULTADOField;
            }
            set {
                this.fGRESULTADOField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DSMENSAJE {
            get {
                return this.dSMENSAJEField;
            }
            set {
                this.dSMENSAJEField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ERRORMATRICESITEMS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public typeErrorMatricesItems[] ERRORES {
            get {
                return this.eRRORESField;
            }
            set {
                this.eRRORESField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.MatricesItems.ActualizarItemsCompania")]
    public partial class ACTUALIZARITEMSCOMPANIA {
        
        private ArrayOfITEMCOMPANIAACTITEMCOMPANIAACT[] iTEMSCOMPANIAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ITEMCOMPANIAACT", IsNullable=false)]
        public ArrayOfITEMCOMPANIAACTITEMCOMPANIAACT[] ITEMSCOMPANIA {
            get {
                return this.iTEMSCOMPANIAField;
            }
            set {
                this.iTEMSCOMPANIAField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.MatricesItems.ActualizarItemsCompania")]
    public partial class ArrayOfITEMCOMPANIAACTITEMCOMPANIAACT {
        
        private string cDITEMField;
        
        private decimal cDTIPOMERCANCIAField;
        
        private string dSITEMField;
        
        private string cDTIPOField;
        
        private decimal cDSUBPARTIDAField;
        
        private string cDUNIDADCOMERCIALField;
        
        private string cDUNIDADMEDIDAField;
        
        private decimal nMCONVERSIONField;
        
        private string sNCOMPONENTESField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDITEM {
            get {
                return this.cDITEMField;
            }
            set {
                this.cDITEMField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CDTIPOMERCANCIA {
            get {
                return this.cDTIPOMERCANCIAField;
            }
            set {
                this.cDTIPOMERCANCIAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DSITEM {
            get {
                return this.dSITEMField;
            }
            set {
                this.dSITEMField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDTIPO {
            get {
                return this.cDTIPOField;
            }
            set {
                this.cDTIPOField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CDSUBPARTIDA {
            get {
                return this.cDSUBPARTIDAField;
            }
            set {
                this.cDSUBPARTIDAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDUNIDADCOMERCIAL {
            get {
                return this.cDUNIDADCOMERCIALField;
            }
            set {
                this.cDUNIDADCOMERCIALField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDUNIDADMEDIDA {
            get {
                return this.cDUNIDADMEDIDAField;
            }
            set {
                this.cDUNIDADMEDIDAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal NMCONVERSION {
            get {
                return this.nMCONVERSIONField;
            }
            set {
                this.nMCONVERSIONField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SNCOMPONENTES {
            get {
                return this.sNCOMPONENTESField;
            }
            set {
                this.sNCOMPONENTESField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.MatricesItems.Matriz")]
    public partial class MATRIZ {
        
        private MATRIZCOMPONENTE[] cOMPONENTEField;
        
        private string cDITEMField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("COMPONENTE")]
        public MATRIZCOMPONENTE[] COMPONENTE {
            get {
                return this.cOMPONENTEField;
            }
            set {
                this.cOMPONENTEField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDITEM {
            get {
                return this.cDITEMField;
            }
            set {
                this.cDITEMField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.MatricesItems.Matriz")]
    public partial class MATRIZCOMPONENTE {
        
        private string cDITEMField;
        
        private decimal nMCANTIDADCONSField;
        
        private decimal nMDESPERDICIOField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDITEM {
            get {
                return this.cDITEMField;
            }
            set {
                this.cDITEMField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal NMCANTIDADCONS {
            get {
                return this.nMCANTIDADCONSField;
            }
            set {
                this.nMCANTIDADCONSField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal NMDESPERDICIO {
            get {
                return this.nMDESPERDICIOField;
            }
            set {
                this.nMDESPERDICIOField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.MatricesItems.InfoMatriz")]
    public partial class INFOMATRIZ {
        
        private INFOMATRIZINFOCOMPONENTE[] iNFOCOMPONENTEField;
        
        private string cDITEMField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("INFOCOMPONENTE")]
        public INFOMATRIZINFOCOMPONENTE[] INFOCOMPONENTE {
            get {
                return this.iNFOCOMPONENTEField;
            }
            set {
                this.iNFOCOMPONENTEField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDITEM {
            get {
                return this.cDITEMField;
            }
            set {
                this.cDITEMField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.MatricesItems.InfoMatriz")]
    public partial class INFOMATRIZINFOCOMPONENTE {
        
        private string cDITEMField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDITEM {
            get {
                return this.cDITEMField;
            }
            set {
                this.cDITEMField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.MatricesItems.InsertarItemsCompania")]
    public partial class INSERTARITEMSCOMPANIA {
        
        private ArrayOfITEMCOMPANIAINSTITEMCOMPANIAINST[] iTEMSCOMPANIAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ITEMCOMPANIAINST", IsNullable=false)]
        public ArrayOfITEMCOMPANIAINSTITEMCOMPANIAINST[] ITEMSCOMPANIA {
            get {
                return this.iTEMSCOMPANIAField;
            }
            set {
                this.iTEMSCOMPANIAField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.MatricesItems.InsertarItemsCompania")]
    public partial class ArrayOfITEMCOMPANIAINSTITEMCOMPANIAINST {
        
        private string cDITEMField;
        
        private decimal cDTIPOMERCANCIAField;
        
        private string dSITEMField;
        
        private string cDTIPOField;
        
        private decimal cDSUBPARTIDAField;
        
        private string cDUNIDADCOMERCIALField;
        
        private string cDUNIDADMEDIDAField;
        
        private decimal nMCONVERSIONField;
        
        private string sNCOMPONENTESField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDITEM {
            get {
                return this.cDITEMField;
            }
            set {
                this.cDITEMField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CDTIPOMERCANCIA {
            get {
                return this.cDTIPOMERCANCIAField;
            }
            set {
                this.cDTIPOMERCANCIAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DSITEM {
            get {
                return this.dSITEMField;
            }
            set {
                this.dSITEMField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDTIPO {
            get {
                return this.cDTIPOField;
            }
            set {
                this.cDTIPOField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CDSUBPARTIDA {
            get {
                return this.cDSUBPARTIDAField;
            }
            set {
                this.cDSUBPARTIDAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDUNIDADCOMERCIAL {
            get {
                return this.cDUNIDADCOMERCIALField;
            }
            set {
                this.cDUNIDADCOMERCIALField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDUNIDADMEDIDA {
            get {
                return this.cDUNIDADMEDIDAField;
            }
            set {
                this.cDUNIDADMEDIDAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal NMCONVERSION {
            get {
                return this.nMCONVERSIONField;
            }
            set {
                this.nMCONVERSIONField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SNCOMPONENTES {
            get {
                return this.sNCOMPONENTESField;
            }
            set {
                this.sNCOMPONENTESField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.MatricesItems.MatrizMasivo")]
    public partial class MATRIZMATRIZ {
        
        private MATRIZMATRIZCOMPONENTE[] cOMPONENTEField;
        
        private string cDITEMField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("COMPONENTE")]
        public MATRIZMATRIZCOMPONENTE[] COMPONENTE {
            get {
                return this.cOMPONENTEField;
            }
            set {
                this.cOMPONENTEField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDITEM {
            get {
                return this.cDITEMField;
            }
            set {
                this.cDITEMField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Mensajes.MatricesItems.MatrizMasivo")]
    public partial class MATRIZMATRIZCOMPONENTE {
        
        private string cDITEMField;
        
        private decimal nMCANTIDADCONSField;
        
        private decimal nMDESPERDICIOField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CDITEM {
            get {
                return this.cDITEMField;
            }
            set {
                this.cDITEMField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal NMCANTIDADCONS {
            get {
                return this.nMCANTIDADCONSField;
            }
            set {
                this.nMCANTIDADCONSField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal NMDESPERDICIO {
            get {
                return this.nMDESPERDICIOField;
            }
            set {
                this.nMDESPERDICIOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ActualizarItemCompletedEventHandler(object sender, ActualizarItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public typeResultadoMatricesItems Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((typeResultadoMatricesItems)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InsertarComponenteCompletedEventHandler(object sender, InsertarComponenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarComponenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarComponenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public typeResultadoMatricesItems Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((typeResultadoMatricesItems)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ModificarComponenteCompletedEventHandler(object sender, ModificarComponenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificarComponenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModificarComponenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public typeResultadoMatricesItems Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((typeResultadoMatricesItems)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EliminarComponenteCompletedEventHandler(object sender, EliminarComponenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarComponenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarComponenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public typeResultadoMatricesItems Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((typeResultadoMatricesItems)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InsertarItemCompletedEventHandler(object sender, InsertarItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public typeResultadoMatricesItems Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((typeResultadoMatricesItems)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ModificarComponentePorEliminacionCompletedEventHandler(object sender, ModificarComponentePorEliminacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificarComponentePorEliminacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModificarComponentePorEliminacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public typeResultadoMatricesItems Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((typeResultadoMatricesItems)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ModificarComponentePorEliminacionMasivoCompletedEventHandler(object sender, ModificarComponentePorEliminacionMasivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificarComponentePorEliminacionMasivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModificarComponentePorEliminacionMasivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public typeResultadoMatricesItems Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((typeResultadoMatricesItems)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591